name: Deploy Static Site to GitHub Pages

on:
  push:
    branches:
      - main  # or your source branch

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Disable Jekyll
        run: echo "" > .nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # root of your repo (where index.html is)
